# -*- coding: utf-8 -*-
"""MosModData_preprocess .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vUbIniSpUWlChzJ_ZALPSztB_UNOuwH
"""

from google.colab import drive
drive.mount('/content/drive')



# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive/data_sets/dico_nifty_preprocessing

# Part 1: from the raw nifty to 0-255 values

"""
preprocess_mosmed.py
--------------------
Minimal preprocessing for MosMedData NIfTI files.
Saves preprocessed output as .nii.gz, preserving affine and header.

Input volume shape: (512, 512, z)  — x, y, z

Pipeline per scan:
  1. Load NIfTI
  2. HU window [-1000, 400]
  3. Normalize to [0, 255] uint8
  4. Save as .nii.gz  (same affine + header, uint8 data)

Output per scan:
  .nii.gz with shape (512, 512, z)  uint8  values in [0, 255]

# ── What this code does NOT do ────────────────────────────────────────────────
# 1. Does NOT reorient to RAS+ — scan orientation is kept as-is
# 2. Does NOT resample — voxel spacing unchanged, neither in-plane nor z
# 3. Does NOT filter empty slices — all z slices kept, including air/table
# 4. Does NOT resize slices — spatial dims stay at native resolution (512x512)
# 5. Does NOT convert to 3 channels — output is single channel grayscale
# 6. Does NOT apply ImageNet normalization — raw [0, 255] uint8, no mean/std
# 7. Does NOT validate HU range — no check that values are actually in HU
# 8. Does NOT check orientation codes — no warning if scan is not RAS+
# 9. Does NOT handle 4D volumes — will fail if data.ndim != 3
"""

import numpy as np
import nibabel as nib
from pathlib import Path

HU_MIN = -1000
HU_MAX =  400


def preprocess_scan(path, verbose=True):
    """
    Parameters
    ----------
    path    : str or Path  — .nii or .nii.gz file
    verbose : bool

    Returns
    -------
    out_img : Nifti1Image  preprocessed, uint8, shape (512, 512, z)
    meta    : dict         scan metadata
    """
    # 1. Load
    img     = nib.load(str(path))
    header  = img.header
    affine  = img.affine
    data    = img.get_fdata(dtype=np.float32)   # shape (512, 512, z)
    spacing = np.array(header.get_zooms()[:3], dtype=np.float32)

    if verbose:
        print(f"Loaded  : {Path(path).name}")
        print(f"Shape   : {data.shape}  (x, y, z)")
        print(f"Spacing : {spacing} mm")
        print(f"HU range: [{data.min():.1f}, {data.max():.1f}]")

    # 2. HU window [-1000, 400]
    data = np.clip(data, HU_MIN, HU_MAX)

    # 3. Normalize to [0, 255]
    data = (data - HU_MIN) / (HU_MAX - HU_MIN) * 255.0
    data = np.round(data).astype(np.uint8)

    if verbose:
        print(f"Range   : [{data.min()}, {data.max()}]  uint8")

    # 4. Build output NIfTI — same affine, update header dtype
    out_header = header.copy()
    out_header.set_data_dtype(np.uint8)

    out_img = nib.Nifti1Image(data, affine=affine, header=out_header)

    meta = {
        "path":      str(path),
        "shape":     data.shape,
        "spacing":   spacing.tolist(),
        "n_slices":  data.shape[2],
        "hu_window": (HU_MIN, HU_MAX),
    }

    return out_img, meta


def preprocess_dataset(input_dir, output_dir, verbose=False):
    """
    Preprocess all NIfTI files in input_dir and save as .nii.gz.

    Parameters
    ----------
    input_dir  : str — folder containing .nii / .nii.gz files
    output_dir : str — folder to save preprocessed .nii.gz files
    """
    input_dir  = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    nii_files = sorted(
        list(input_dir.glob("*.nii")) +
        list(input_dir.glob("*.nii.gz"))
    )

    print(f"Found {len(nii_files)} files in {input_dir}")

    all_meta = {}

    for i, path in enumerate(nii_files):
        stem     = path.name.replace(".nii.gz", "").replace(".nii", "")
        out_path = output_dir / f"{stem}.nii.gz"

        if out_path.exists():
            print(f"[{i+1}/{len(nii_files)}] Skipping {stem} (exists)")
            continue

        try:
            out_img, meta  = preprocess_scan(path, verbose=verbose)
            all_meta[stem] = meta
            nib.save(out_img, str(out_path))
            print(f"[{i+1}/{len(nii_files)}] Saved {stem}.nii.gz  "
                  f"shape={out_img.shape}")
        except Exception as e:
            print(f"[{i+1}/{len(nii_files)}] ERROR {stem}: {e}")

    # Save metadata
    meta_path = output_dir / "metadata.npy"
    np.save(str(meta_path), all_meta)
    print(f"Metadata saved → {meta_path}")
    print("Done.")


# ── Example usage ─────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Single scan
    out_img, meta = preprocess_scan("study_0934.nii")
    nib.save(out_img, "study_0934_preprocessed.nii.gz")
    print(meta)

    # Full dataset
    # preprocess_dataset(
    #     input_dir  = "mosmed/CT-0",
    #     output_dir = "preprocessed/CT-0",
    # )

# just check that the values of a random slice are between 0-255


import random
import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

path = "study_0934_preprocessed.nii.gz"

img = nib.load(path)
vol = img.get_fdata()

# pick random axial slice
z = random.randint(0, vol.shape[2] - 1)
sl = vol[:, :, z]

print("Volume shape:", vol.shape)
print("Chosen slice:", z)
print("Slice min/max:", sl.min(), sl.max())

plt.figure(figsize=(6, 4))
plt.hist(sl.ravel(), bins=50)
plt.xlabel("Intensity")
plt.ylabel("Count")
plt.title(f"Histogram of intensities - slice {z}")
plt.show()

# Part 2 - from the preprocess nifties (0-255) to npy embbedings
"""
embeddings_final.py
-------------------
Extract DINOv2 CLS embeddings from preprocessed 3D NIfTI files.

Expected input:
  - .nii or .nii.gz files
  - uint8 values in [0, 255]
  - shape (H, W, Z)
  - single-channel grayscale

Output per scan:
  stem.npy   shape (Z, D)   float32
"""

from pathlib import Path

import nibabel as nib
import numpy as np
import torch
from PIL import Image
from transformers import AutoImageProcessor, AutoModel


def slice_to_pil(sl):
    """
    Convert one 2D grayscale slice to a 3-channel RGB PIL image.

    Parameters
    ----------
    sl : np.ndarray
        Array of shape (H, W), values expected in [0, 255].

    Returns
    -------
    PIL.Image.Image
        RGB image.
    """
    sl = np.clip(sl, 0, 255).astype(np.uint8)
    rgb = np.stack([sl, sl, sl], axis=-1)   # (H, W, 3)
    return Image.fromarray(rgb, mode="RGB")


def get_slice_embeddings_cls(volume_3d, processor, model, device, batch_size=16):
    """
    Extract CLS embeddings for all axial slices in a 3D volume.

    Parameters
    ----------
    volume_3d : np.ndarray
        Shape (H, W, Z), values in [0, 255].
    processor : AutoImageProcessor
    model : AutoModel
    device : torch.device
    batch_size : int

    Returns
    -------
    np.ndarray
        Shape (Z, D), float32
    """
    z_dim = volume_3d.shape[2]
    all_embeddings = []

    images = [slice_to_pil(volume_3d[:, :, z]) for z in range(z_dim)]

    for start in range(0, z_dim, batch_size):
        batch_imgs = images[start:start + batch_size]
        inputs = processor(images=batch_imgs, return_tensors="pt")

        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
            cls = outputs.last_hidden_state[:, 0, :]   # (B, D)

        all_embeddings.append(cls.cpu().numpy().astype(np.float32))

    return np.concatenate(all_embeddings, axis=0)   # (Z, D)


def extract_embeddings(input_dir, output_dir, model_dir, batch_size=16):
    """
    Process all NIfTI files in input_dir and save embeddings as .npy files.

    Parameters
    ----------
    input_dir : str or Path
        Folder containing preprocessed .nii / .nii.gz files.
    output_dir : str or Path
        Folder where .npy embeddings will be saved.
    model_dir : str or Path
        Path or HF identifier for DINOv2 model.
    batch_size : int
        Number of slices per forward pass.
    """
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    nii_files = sorted(list(input_dir.glob("*.nii")) + list(input_dir.glob("*.nii.gz")))

    if len(nii_files) == 0:
        print(f"No NIfTI files found in {input_dir}")
        return

    print(f"Found {len(nii_files)} files in {input_dir}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    processor = AutoImageProcessor.from_pretrained(model_dir)
    model = AutoModel.from_pretrained(model_dir).to(device)
    model.eval()

    for i, nii_path in enumerate(nii_files, start=1):
        stem = nii_path.name.replace(".nii.gz", "").replace(".nii", "")
        out_path = output_dir / f"{stem}.npy"

        if out_path.exists():
            print(f"[{i}/{len(nii_files)}] Skipping {stem} (exists)")
            continue

        try:
            vol = nib.load(str(nii_path)).get_fdata(dtype=np.float32)

            if vol.ndim != 3:
                raise ValueError(f"Expected 3D volume, got shape {vol.shape}")

            emb = get_slice_embeddings_cls(
                volume_3d=vol,
                processor=processor,
                model=model,
                device=device,
                batch_size=batch_size,
            )

            np.save(str(out_path), emb)
            print(f"[{i}/{len(nii_files)}] Saved {out_path.name}  shape={emb.shape}")

        except Exception as e:
            print(f"[{i}/{len(nii_files)}] ERROR {stem}: {e}")

    print("Done.")


INPUT_DIR = "."
OUTPUT_DIR = "."
MODEL_DIR = "../DINO_jaws_cancer/CNN_LSTM/dinov3_b16_weights"

extract_embeddings(INPUT_DIR, OUTPUT_DIR, MODEL_DIR, batch_size=16)

!ls ../DINO_jaws_cancer/CNN_LSTM/dinov3_b16_weights

# just shows the shape of the npy output
import numpy as np

arr = np.load("study_0934_preprocessed.npy")
print(arr.shape)