# -*- coding: utf-8 -*-
"""finall_pipline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfaibpVAde5QaToAM6NZE9-0Qsgoch8Y
"""

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  תא 0 — הגדרות סביבה                                       ║
# ╚══════════════════════════════════════════════════════════════╝
from google.colab import drive
drive.mount('/content/drive')

# Install other dependencies
!pip install aeon pyyaml -q       # ← נדרש ל-MultiRocket ו-Module 4
!pip install transformers -q
!pip install sktime
!pip install aeon

# %cd /content/drive/MyDrive/mini/sliceheads_project

!pip install -e . -q

# -*- coding: utf-8 -*-
"""
sliceheads — Full Pipeline Notebook
Design Document v0.3 | Demonstration Notebook 1 of 3

מכסה את כל השלבים מקצה לקצה:
  Module 1 → יצירת HDF5 מ-NIfTI
  Module 2 → אימון ראשי סיווג
  Module 3 → הערכה (metrics + LOO)
  Module 4 → אופטימיזציית Hyperparameters
  Module 6 → שמירת תוצאות מלאה


"""



# נתיבים ← שני לפי המיקום שלך
PROJECT_DIR   = "/content/drive/MyDrive/sliceheads_project"
CT0_DIR       = "/content/drive/MyDrive/mini/studies_mini/CT-0"
CT1_DIR       = "/content/drive/MyDrive/mini/studies_mini/CT-1"
ENCODER_PATH  = "/content/drive/MyDrive/mini/dinov3_b16_weights"
H5_PATH       = f"{PROJECT_DIR}/output_mini.h5"
SPLIT_FILE    = f""
CONFIG_PATH   = f"{PROJECT_DIR}/config.yaml"
RESULTS_DIR   = f"{PROJECT_DIR}/results"

import os
print("📂 Project dir:", PROJECT_DIR)
print("✅" if os.path.exists(ENCODER_PATH) else "❌", "Encoder:", ENCODER_PATH)
print("✅" if os.path.exists(CT0_DIR)      else "❌", "CT-0:",    CT0_DIR)
print("✅" if os.path.exists(CT1_DIR)      else "❌", "CT-1:",    CT1_DIR)

import os
from pathlib import Path

print("🔍 בודק נתיבים...")
for name, path in [("Encoder", ENCODER_PATH), ("CT-0", CT0_DIR), ("CT-1", CT1_DIR)]:
    icon = "✅" if os.path.exists(path) else "❌"
    print(f"  {icon} {name}: {path}")

# ── ספירת קבצים ──
for name, d in [("CT-0", CT0_DIR), ("CT-1", CT1_DIR)]:
    nii = sorted(list(Path(d).glob("*.nii")) + list(Path(d).glob("*.nii.gz")))
    print(f"\n📂 {name} — {len(nii)} קבצים:")
    for f in nii:
        print(f"    {f.name}")


# ────────────────────────────────────────────────────────────
# אפשרות א: קובץ טקסט
# ────────────────────────────────────────────────────────────
# צרי קובץ בשם splits.txt ב-Drive עם תוכן כזה:
#
#   study_001.nii.gz  train
#   study_002.nii.gz  train
#   study_003.nii.gz  val
#   study_004.nii.gz  test
#
# ואז:


# תוכלי גם ליצור את הקובץ ישירות מהנוטבוק:
# (מחקי את ה-# ומלאי את שמות הקבצים האמיתיים שלך)
"""
splits_content = '''# splits for MosMedData
# format: <filename>  <split>

# CT-0 (label=0)
study_001.nii.gz  train
study_002.nii.gz  train
study_003.nii.gz  val
study_004.nii.gz  test

# CT-1 (label=1)
study_099.nii.gz  train
study_100.nii.gz  val
study_101.nii.gz  test
'''
with open(SPLIT_FILE, "w") as f:
    f.write(splits_content)
print(f"✅ קובץ splits נוצר: {SPLIT_FILE}")
"""

# ────────────────────────────────────────────────────────────
# אפשרות ב: רשימות ידניות
# ────────────────────────────────────────────────────────────
# מלאי את שמות הקבצים לפי מה שיש לך
TRAIN_FILES = [
    "עותק של study_0001.nii",
    "עותק של study_0256.nii",
    "עותק של study_0257.nii",
]
VAL_FILES = [
    "עותק של study_0255.nii",
    "עותק של study_0002.nii",
]
TEST_FILES = [
    "עותק של study_0258.nii",
    "עותק של study_0003.nii",
]

# ============================================================
# תא 5 — תצוגה מקדימה של ה-split לפני הרצה
# ============================================================
from sliceheads.module1 import parse_split_file, build_split_dict

print("\n📋 תצוגה מקדימה של Split:")
print("-" * 40)

# -- שני את הבלוק הרלוונטי לאפשרות שבחרת --

# אפשרות א — קובץ טקסט:
# split_dict = parse_split_file(SPLIT_FILE)

# אפשרות ב — רשימות ידניות:
split_dict = build_split_dict(
    train_files=TRAIN_FILES,
    val_files=VAL_FILES,
    test_files=TEST_FILES,
)

# אפשרות ג — חלוקה אוטומטית 60/20/20 (train/val/test):
# import random
# all_stems = [nf.name for nf in all_nii]
# random.seed(42)
# random.shuffle(all_stems)
# n = len(all_stems)
# n_train = int(0.6 * n)
# n_val   = int(0.2 * n)
# split_dict = {}
# for i, fname in enumerate(all_stems):
#     if i < n_train:
#         split_dict[fname] = "train"
#     elif i < n_train + n_val:
#         split_dict[fname] = "val"
#     else:
#         split_dict[fname] = "test"

# ── הצג את ההקצאה לכל קובץ ──
all_nii = []
for d in [CT0_DIR, CT1_DIR]:
    all_nii += sorted(list(Path(d).glob("*.nii")) + list(Path(d).glob("*.nii.gz")))

for nf in all_nii:
    stem = nf.name.replace(".nii.gz","").replace(".nii","")
    sp   = split_dict.get(nf.name) or split_dict.get(stem) or ""
    icon = {"train": "🔵", }.get(sp.split()[0] if sp.strip() else "", "⚪")
    print(f"  {icon} {nf.parent.name}/{nf.name}  →  {sp}")

# ============================================================
# תא 6 — הרצת Pipeline
# ============================================================
from sliceheads.module1 import EmbeddingPipeline

print("\n🚀 מאתחלת Pipeline...")

try:
    pipeline = EmbeddingPipeline(model_source=ENCODER_PATH, batch_size=4)
    print("✅ Pipeline אותחל!")
    print("-" * 60)

    # ── אפשרות א — קובץ טקסט ──
    # pipeline.run(
    #     input_dirs=[CT0_DIR, CT1_DIR],
    #     output_h5_path=OUTPUT_H5,
    #     dir_to_label={"CT-0": 0, "CT-1": 1},
    #     split_file=SPLIT_FILE,
    # )

    # ── אפשרות ב — רשימות ידניות ──
    pipeline.run(
        input_dirs=[CT0_DIR, CT1_DIR],
        output_h5_path=H5_PATH ,
        dir_to_label={"CT-0": 0, "CT-1": 1},
        train_files=TRAIN_FILES,
        val_files=VAL_FILES,
        test_files=TEST_FILES,
    )

    # ── אפשרות ג — חלוקה אוטומטית 60/20/20 ──
    # pipeline.run(
    #     input_dirs=[CT0_DIR, CT1_DIR],
    #     output_h5_path=H5_PATH,
    #     dir_to_label={"CT-0": 0, "CT-1": 1},
    #     split_dict=split_dict,
    # )

    print("-" * 60)
    print(f"🎉 Module 1 סיים!")
    print(f"📦 {H5_PATH}")

except Exception as e:
    import traceback
    print("❌ שגיאה:")
    traceback.print_exc()


import h5py

print("\n🔍 סריקת HDF5:")
print("=" * 60)

with h5py.File(H5_PATH , "r") as f:
    samples = sorted(k for k in f.keys() if k.startswith("sample_"))
    labels  = [int(f[k]["label"][()]) for k in samples]
    splits  = {}
    rows    = []
    for k in samples:
        sp  = f[k].attrs.get("split", "?")
        if isinstance(sp, bytes): sp = sp.decode()
        pid = f[k].attrs.get("patient_id", k)
        if isinstance(pid, bytes): pid = pid.decode()
        splits[sp] = splits.get(sp, 0) + 1
        rows.append((k, pid, int(f[k]["label"][()]), sp, f[k]["embeddings"].shape))

    print(f"📊 Samples:      {len(samples)}")
    print(f"🏷️  Labels:       0={labels.count(0)}, 1={labels.count(1)}")
    print(f"📂 Splits:       {splits}")
    print(f"📐 Embed dim:    {f.attrs.get('embedding_dim')}")
    print(f"🧠 Backbone:     {f.attrs.get('backbone_name')}")
    print(f"✅ mean_embedding: {'mean_embedding' in f}")
    print()
    print(f"{'sample_id':<12} {'patient_id':<25} {'label':^6} {'split':^8} {'shape'}")
    print("-" * 70)
    for sid, pid, lbl, sp, shape in rows:
        icon = {"train":"🔵","val":"🟡","test":"🟢"}.get(sp,"⚪")
        print(f"{sid:<12} {pid:<25} {lbl:^6} {icon}{sp:<7} {shape}")


from sliceheads.module1 import validate_h5

print("\n🔬 Validation:")
try:
    validate_h5(H5_PATH )
except ValueError as e:
    print(f"❌ {e}")

print("\n" + "=" * 60)
print("🏁 בדיקת Module 1 הושלמה!")
print(f"📦 קובץ מוכן ל-Module 2: {H5_PATH }")
print("=" * 60)



# ╔══════════════════════════════════════════════════════════════╗
# ║  Module 2 — אימון ראשי סיווג                               ║
# ╚══════════════════════════════════════════════════════════════╝

# ── תא 5: import כל הראשים ─────────────────────────────────────
from sliceheads.module2 import (
    MeanPoolClassifier,
    MaxPoolClassifier,
    GeMPoolClassifier,
    ABMILClassifier,
    GatedABMILClassifier,
    DSMILClassifier,
    TransformerMILClassifier,
    InceptionTimeClassifier,
    ALSTMFCNClassifier,
    MultiRocketHydraClassifier,
)
print("✅ Module 2 יובא בהצלחה")

# ── תא 6: הגדרת הראשים ─────────────────────────────────────────
print("\n" + "="*60)
print("  Module 2 — הגדרת ראשים (default hyperparameters)")
print("="*60)

# ← ניתן להפעיל/לבטל ראשים לפי הצורך
HEADS = {
    "MeanPool":   MeanPoolClassifier(C=1.0),
    "MaxPool":    MaxPoolClassifier(C=1.0),
    "GeM":        GeMPoolClassifier(p=3.0, C=1.0),
    "ABMIL":      ABMILClassifier(hidden_dim=128, dropout=0.25,
                                   lr=3e-4, max_epochs=100, patience=15),
    "GatedABMIL": GatedABMILClassifier(hidden_dim=128, dropout=0.25,
                                        lr=3e-4, max_epochs=100, patience=15),
    "DSMIL":      DSMILClassifier(hidden_dim=128, dropout=0.25,
                                   lambda_instance=0.5, lr=3e-4,
                                   max_epochs=100, patience=15),
    "TransformerMIL": TransformerMILClassifier(d_model=256, num_layers=2,
                                                n_heads=4, pooling="cls",
                                                dropout=0.25, lr=3e-4,
                                                max_epochs=100, patience=15),
    "InceptionTime": InceptionTimeClassifier(n_filters=32, depth=3,
                                              dropout=0.25, lr=3e-4,
                                              max_epochs=100, patience=15),
    "ALSTMFCN":   ALSTMFCNClassifier(hidden_dim=128, dropout=0.25,
                                      lr=3e-4, max_epochs=100, patience=15),
    # "MultiRocket": MultiRocketHydraClassifier(n_kernels=6250),
    # ↑ הסר # אם aeon מותקן (!pip install aeon)
}
print(f"📋 {len(HEADS)} ראשים מוגדרים: {list(HEADS.keys())}")

# ── תא 7: אימון ────────────────────────────────────────────────
print("\n" + "="*60)
print("  Module 2 — אימון")
print("="*60)

FITTED_HEADS = {}
for name, head in HEADS.items():
    print(f"\n▶ {name}...")
    try:
        head.fit_h5(H5_PATH)
        FITTED_HEADS[name] = head
        print(f"  ✅ הושלם")
    except Exception as e:
        import traceback
        print(f"  ❌ שגיאה:")
        traceback.print_exc()

print(f"\n✅ אומנו {len(FITTED_HEADS)}/{len(HEADS)} ראשים")

# ╔══════════════════════════════════════════════════════════════╗
# ║  Module 3 — הערכה                                          ║
# ╚══════════════════════════════════════════════════════════════╝

# ── תא 8: הערכה על test split ──────────────────────────────────
from sliceheads.module3 import evaluate, print_metrics, print_comparison_table

print("\n" + "="*60)
print("  Module 3 — הערכה (test split)")
print("="*60)

ALL_RESULTS = {}
for name, head in FITTED_HEADS.items():
    try:
        res = evaluate(
            head=head,
            h5_path=H5_PATH,
            eval_split="test",
            operating_point=0.5,    # קבוע לפי design doc עמ' 10
            n_bootstraps=2000,      # 95% bootstrap CI לפי design doc עמ' 10
            random_seed=42,
        )
        print_metrics(res)
        ALL_RESULTS[name] = res
    except Exception as e:
        print(f"❌ {name}: {e}")

# ── תא 9: טבלת השוואה ──────────────────────────────────────────
if len(ALL_RESULTS) >= 2:
    print_comparison_table(ALL_RESULTS)

# ╔══════════════════════════════════════════════════════════════╗
# ║  Module 4 — Hyperparameter Optimization                    ║
# ╚══════════════════════════════════════════════════════════════╝

# ── תא 10: כתיבת config.yaml ───────────────────────────────────
print("\n" + "="*60)
print("  Module 4 — HPO")
print("="*60)

CONFIG_YAML = f"""
experiment:
  name: ct_embedding_head_benchmark
  task: binary_classification
  primary_metric: roc_auc

confidence_interval:
  n_bootstraps: 2000
  ci: 0.95
  random_seed: 42

data:
  h5_path: {H5_PATH}
  embedding_key: embeddings
  label_attr: label
  split_attr: split
  splits:
    train: train
    validation: val
    test: test

search_strategy: grid
n_random_configs: 20

training:
  random_seed: 42
  selection_metric: roc_auc
  final_evaluation_split: test
  use_class_weights: true

heads:
  MeanPoolClassifier:
    enabled: true
    family: pooling
    hyperparameters:
      C: [0.001, 0.01, 0.1, 1, 10, 100]
      class_weight: ["balanced", null]
      classifier: ["logistic_regression"]

  MaxPoolClassifier:
    enabled: true
    family: pooling
    hyperparameters:
      C: [0.001, 0.01, 0.1, 1, 10, 100]
      class_weight: ["balanced", null]
      classifier: ["logistic_regression"]

  GeMPoolClassifier:
    enabled: true
    family: pooling
    hyperparameters:
      p: [1.0, 1.5, 2, 3, 4, 6, 8]
      C: [0.001, 0.01, 0.1, 1, 10, 100]
      class_weight: ["balanced", null]
      classifier: ["logistic_regression"]
"""

with open(CONFIG_PATH, "w") as f:
    f.write(CONFIG_YAML)
print(f"✅ config.yaml נכתב: {CONFIG_PATH}")

# ── תא 11: הרצת HPO ────────────────────────────────────────────
# הרץ תחילה על ראשי הpooling בלבד (מהיר) לפני PyTorch heads

from sliceheads.module4 import run_benchmark

print("\n▶ מריץ HPO על ראשי pooling...")
HPO_RESULTS = run_benchmark(
    config_path=CONFIG_PATH,
    h5_path=H5_PATH,
    output_dir=RESULTS_DIR,
    skip_hpo=False,    # ← True לדלג על grid search ולאמן עם defaults
)

# ── תא 12: תוצאות HPO ──────────────────────────────────────────
print("\n📊 Best hyperparameters per head:")
for name, res in HPO_RESULTS.items():
    print(f"  {name}: {res['best_params']}  (val AUC={res['val_score']:.4f})")

# ╔══════════════════════════════════════════════════════════════╗
# ║  Module 6 — שמירת תוצאות מלאה                             ║
# ╚══════════════════════════════════════════════════════════════╝

# ── תא 13: persist_results ─────────────────────────────────────
from sliceheads.module6 import persist_results, load_results_directory
import yaml

print("\n" + "="*60)
print("  Module 6 — Results Persistence")
print("="*60)

# איחוד תוצאות Module 3 + Module 4 ל-format אחיד
COMBINED = {}
for name, res in ALL_RESULTS.items():
    hpo = HPO_RESULTS.get(name, {})
    COMBINED[name] = {
        "metrics":     res,
        "best_params": hpo.get("best_params", {}),
        "val_score":   hpo.get("val_score", float("nan")),
    }
# הוסף ראשים שרצו ב-HPO אבל לא ב-evaluate הידני
for name, res in HPO_RESULTS.items():
    if name not in COMBINED:
        COMBINED[name] = res

# טען את ה-config המשמש
with open(CONFIG_PATH) as f:
    config_used = yaml.safe_load(f)

written = persist_results(
    all_results=COMBINED,
    output_dir=RESULTS_DIR,
    config=config_used,
    importance_results=None,   # ← העבר תוצאות Module 5 כאן אם רלוונטי
    random_seed=42,
)

# ── תא 14: אימות תוצאות ────────────────────────────────────────
print("\n🔍 אימות תיקיית results/:")
loaded = load_results_directory(RESULTS_DIR)

print(f"  📊 metrics.csv:           {len(loaded.get('metrics', []))} שורות")
print(f"  📋 test_predictions.csv:  {len(loaded.get('test_predictions', []))} שורות")
print(f"  ⚙️  hyperparameters.json:  {list(loaded.get('hyperparameters', {}).keys())}")
print(f"  🖥️  run_metadata:          Python {loaded.get('run_metadata', {}).get('python_version', '?')}")
print(f"  📄 config_used.yaml:      {'✅' if loaded.get('config_used') else '❌'}")

print(f"\n📁 כל הקבצים נשמרו ב: {RESULTS_DIR}")
for name, path in written.items():
    size = os.path.getsize(path) if os.path.exists(path) else 0
    print(f"  ✅ {name:<25} ({size:,} bytes)")

# ╔══════════════════════════════════════════════════════════════╗
# ║  סיכום מלא                                                 ║
# ╚══════════════════════════════════════════════════════════════╝

print("\n" + "="*60)
print("  Full Pipeline — סיכום")
print("="*60)
print(f"  Module 1: ✅  HDF5 עם {len(samples)} samples")
print(f"  Module 2: ✅  {len(FITTED_HEADS)} ראשים אומנו")
print(f"  Module 3: ✅  הערכה על test split")
print(f"  Module 4: ✅  HPO הושלם")
print(f"  Module 6: ✅  תוצאות נשמרו ב-{RESULTS_DIR}")
print()
print("📊 ROC-AUC לפי ראש:")
all_to_show = {**ALL_RESULTS}
# הוסף תוצאות HPO שהכילו evaluate משלהן
for name, res in HPO_RESULTS.items():
    if name not in all_to_show and "metrics" in res:
        all_to_show[name] = res["metrics"]

for name, res in all_to_show.items():
    auc = res.get("roc_auc", float("nan"))
    ci_lo = res.get("roc_auc_ci_lower", float("nan"))
    ci_hi = res.get("roc_auc_ci_upper", float("nan"))
    bp    = HPO_RESULTS.get(name, {}).get("best_params", "default")
    print(f"  {name:<16} AUC={auc:.4f}  "
          f"CI=[{ci_lo:.4f},{ci_hi:.4f}]  best_params={bp}")